USE [master]
GO
/****** Object:  Database [SolicitudesDB]    Script Date: 22/08/2021 02:52:45 p. m. ******/
CREATE DATABASE [SolicitudesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SolicitudesDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SolicitudesDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SolicitudesDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SolicitudesDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SolicitudesDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SolicitudesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SolicitudesDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SolicitudesDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SolicitudesDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SolicitudesDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SolicitudesDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SolicitudesDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SolicitudesDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SolicitudesDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SolicitudesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SolicitudesDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SolicitudesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SolicitudesDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SolicitudesDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SolicitudesDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SolicitudesDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SolicitudesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SolicitudesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SolicitudesDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SolicitudesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SolicitudesDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SolicitudesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SolicitudesDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SolicitudesDB] SET RECOVERY FULL 
GO
ALTER DATABASE [SolicitudesDB] SET  MULTI_USER 
GO
ALTER DATABASE [SolicitudesDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SolicitudesDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SolicitudesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SolicitudesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SolicitudesDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SolicitudesDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SolicitudesDB', N'ON'
GO
ALTER DATABASE [SolicitudesDB] SET QUERY_STORE = OFF
GO
USE [SolicitudesDB]
GO
/****** Object:  Table [dbo].[Personas]    Script Date: 22/08/2021 02:52:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personas](
	[UIDPersona] [uniqueidentifier] NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[ApellidoPaterno] [varchar](100) NOT NULL,
	[NumeroTelefono] [varchar](50) NOT NULL,
	[Sexo] [bit] NOT NULL,
	[UIDTipoPersonaRef] [uniqueidentifier] NOT NULL,
	[ApellidoMaterno] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Personas] PRIMARY KEY CLUSTERED 
(
	[UIDPersona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TiposPersonas]    Script Date: 22/08/2021 02:52:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TiposPersonas](
	[UIDTipoPersona] [uniqueidentifier] NOT NULL,
	[TipoPersona] [varchar](100) NOT NULL,
	[Orden] [int] NOT NULL,
 CONSTRAINT [PK_TiposPersonas] PRIMARY KEY CLUSTERED 
(
	[UIDTipoPersona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TiposUsuarios]    Script Date: 22/08/2021 02:52:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TiposUsuarios](
	[UIDTipoUsuario] [uniqueidentifier] NOT NULL,
	[TipoUsuario] [varchar](100) NOT NULL,
	[Orden] [int] NOT NULL,
	[Rango] [int] NOT NULL,
 CONSTRAINT [PK_TiposUsuarios] PRIMARY KEY CLUSTERED 
(
	[UIDTipoUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 22/08/2021 02:52:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[UIDUsuario] [uniqueidentifier] NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[UIDPersonaRef] [uniqueidentifier] NOT NULL,
	[UIDTipoUsuarioRef] [uniqueidentifier] NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[UIDUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Personas]  WITH NOCHECK ADD  CONSTRAINT [FK_Personas_TiposPersonas] FOREIGN KEY([UIDTipoPersonaRef])
REFERENCES [dbo].[TiposPersonas] ([UIDTipoPersona])
GO
ALTER TABLE [dbo].[Personas] NOCHECK CONSTRAINT [FK_Personas_TiposPersonas]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios_Personas] FOREIGN KEY([UIDPersonaRef])
REFERENCES [dbo].[Personas] ([UIDPersona])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK_Usuarios_Personas]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios_TiposUsuarios] FOREIGN KEY([UIDTipoUsuarioRef])
REFERENCES [dbo].[TiposUsuarios] ([UIDTipoUsuario])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK_Usuarios_TiposUsuarios]
GO
USE [master]
GO
ALTER DATABASE [SolicitudesDB] SET  READ_WRITE 
GO
